"""
agent.py — Smart LLM Synthesizer using Gemini.

WHAT THIS MODULE DOES:
  Passes the top 3 BM25 chunks and the user ticket to Gemini 1.5 Flash.
  Gemini reads the chunks, synthesizes a human-friendly response, 
  re-evaluates the request type, and outputs strict JSON.

WHY:
  - Smart triage: Gemini can tell if chunks actually answer the question.
  - Helpful responses: No more raw dump of text; answers are conversational.
  - Resilient: Falls back to the raw chunk template if the API fails.
"""

import json
from loguru import logger
from google import genai
from typing import Literal

from models import TicketInput, TicketOutput, DocChunk, make_escalation
from config import GEMINI_API_KEY, DEFAULT_PRODUCT_AREA

# Initialize Gemini Client
_client = genai.Client(api_key=GEMINI_API_KEY) if GEMINI_API_KEY else None

def generate_response(
    ticket: TicketInput,
    chunks: list[DocChunk],
    product_area: str,
    request_type: Literal["product_issue", "feature_request", "bug", "invalid"],
) -> TicketOutput:
    """
    Generate a smart, grounded response using Gemini 2.5 Flash.
    """
    if not _client:
        logger.warning("No GEMINI_API_KEY found! Falling back to raw template.")
        if not chunks:
            return make_escalation("No relevant docs found.", product_area, request_type) # type: ignore
        return _fallback_template(chunks[0], product_area, request_type)

    if not chunks:
        # Pass empty chunks to Gemini to let it elegantly say "Out of scope / Escalated"
        pass

    # Format top 3 context chunks
    context = ""
    if chunks:
        context = "\n\n".join([f"--- Chunk {i+1} from {c.company} ({c.source}) ---\n{c.text}" for i, c in enumerate(chunks[:3])])
    else:
        context = "NO DOCUMENTATION FOUND FOR THIS ISSUE."

    prompt = f"""You are an expert customer support triage agent for {ticket.company if ticket.company != 'None' else 'HackerRank, Claude, and Visa'}.

TICKET SUBJECT: {ticket.subject}
TICKET ISSUE: {ticket.issue}

SUPPORT DOCUMENTATION (ONLY USE THIS):
{context}

INSTRUCTIONS:
1. Identify the 'request_type' (must be exactly one of: "product_issue", "feature_request", "bug", "invalid").
2. Identify the 'product_area' (e.g., "general_support", "billing", "pro-and-max-plans", etc).
3. If the documentation contains the answer, synthesize a polite, helpful response using ONLY the provided facts. Set status="replied".
4. If the documentation does NOT contain the answer, or if the user is asking something risky/sensitive not covered, set status="escalated" and provide a standard escalation response.
5. Write a short 'justification' for your decision (e.g., "Synthesized from source X" or "Escalated because no relevant docs found").

OUTPUT STRICTLY IN JSON FORMAT matching this exact schema:
{{
  "status": "replied" | "escalated",
  "product_area": "string",
  "response": "string",
  "justification": "string",
  "request_type": "product_issue" | "feature_request" | "bug" | "invalid"
}}
"""

    try:
        response = _client.models.generate_content(
            model='gemini-2.5-flash',
            contents=prompt,
        )
        
        # Clean markdown formatting from JSON
        raw_json = response.text.strip()
        if raw_json.startswith("```json"):
            raw_json = raw_json[7:-3].strip()
        elif raw_json.startswith("```"):
            raw_json = raw_json[3:-3].strip()
            
        data = json.loads(raw_json)
        
        return TicketOutput(**{
            "status": data.get("status", "escalated"),
            "product_area": data.get("product_area", product_area),
            "response": data.get("response", "This issue has been escalated to human support."),
            "justification": data.get("justification", "Generated by AI"),
            "request_type": data.get("request_type", request_type)
        })

    except Exception as e:
        logger.error(f"Gemini API Error: {e}")
        # Fallback to deterministic template if API fails
        if chunks:
            return _fallback_template(chunks[0], product_area, request_type)
        else:
            return make_escalation("API Failed and no chunks found.", product_area, request_type) # type: ignore


def _fallback_template(chunk: DocChunk, product_area: str, request_type: str) -> TicketOutput:
    return TicketOutput(**{
        "status": "replied",
        "product_area": product_area,
        "response": f"Based on our documentation:\n\n{chunk.text.strip()}\n\n(Source: {chunk.source})",
        "justification": "Fallback to raw template due to AI error or missing key.",
        "request_type": request_type
    })
